name: Pelican site CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install language packs
      run: |
        sudo apt-get update
        sudo apt-get install language-pack-zh-hant
    - uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build site
      run: |
        make publish
    - name: Add nojekyll
      run: |
        touch ./output/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REPOSITORY_NAME: twnanda/twnanda.github.io
        BRANCH: master
        FOLDER: output
        CLEAN: true
